#!/usr/bin/python3

'''
walk /cvmfs/singularity.opensciencegrid.org/ and find container metadata
'''

import os
import json
import re
from string import Template
from pprint import pprint

metadata = {}
md_sorted = []


def sort_key(entry):
    key = ''
    if 'category' in entry:
        key += entry['category']
    if 'name' in entry:
        key += entry['name']
    return key


def import_metadata(top_dir, identifier, tag):

    global metadata

    json_file = os.path.join(top_dir, identifier + ':' + tag, '.singularity.d/labels.json')
    if os.path.getsize(json_file) < 10:
        return

    print('Processing {}...'.format(json_file))
    
    # first ensure it has the required metadata
    with open(json_file) as f:
        fdata = json.load(f)

    if 'opensciencegrid.name' in fdata:
        if identifier not in metadata:
            data = {}
            data['identifier'] = identifier
            for k, v in fdata.items():
                newk = re.sub('opensciencegrid\.', '', k)
                data[newk] = v
            data['cvmfs_path'] = os.path.join(top_dir, identifier)
            data['tags'] = []
            metadata[identifier] = data
        metadata[identifier]['tags'].append(tag)


def main():

    top_dir = '/cvmfs/singularity.opensciencegrid.org'
    
    # we have two levels, first one is org
    orgs = os.listdir(top_dir)
    for org in orgs:
        try:
            images = os.listdir(os.path.join(top_dir, org))
        except:
            continue

        for image in images:
            if not os.path.isfile(os.path.join(top_dir, org, image, '.singularity.d/labels.json')):
                continue
            identifier, tag = image.split(':')
            identifier = org + '/' + identifier
            import_metadata(top_dir, identifier, tag)

    # convert the dict to a list and sort it
    for k, v in metadata.items():
        md_sorted.append(v)
    md_sorted.sort(key=sort_key)
    
    pprint(md_sorted)

    # write the tables
    table = ''
    curr_category = None
    for entry in md_sorted:
        if entry['category'] != curr_category:
            curr_category = entry['category']
            table += '\n## {}\n\n'.format(entry['category'])
            table += '| **Name** | **CVMFS Locations** | **Description** |\n'
            table += '|:---------|:--------------------|:----------------|\n'
        locations = ''
        name = '<span style="white-space: nowrap">{}</span>'.format(entry['name'])
        for tag in sorted(entry['tags']):
            if locations != '':
                locations += '<br>'
            locations += '<span style="white-space: nowrap">{}:{}</span>'.format(entry['cvmfs_path'], tag)
        desc = entry['description']
        if 'url' in entry:
            desc += '<br>[Project Website]({})'.format(entry['url'])
        if 'definition_url' in entry:
            desc += '<br>[Container Definition]({})'.format(entry['definition_url'])
        table += '| {} | {} | {} |\n'.format(name, locations, desc)

    
    # the page is a simple template
    with open('container-list.template') as f:
        template = Template(f.read())
   
    with open('../../start/software/available-containers-list.md', 'w') as f:
        f.write(template.substitute(table=table))


if __name__ == '__main__':
    main()

